run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - deadcode
    - varcheck
  disable:
    - revive
    - misspell

linters-settings:
  goimports:
    local-prefixes: suno-wallets

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude:
    - "should have a package comment"
    - "exported .* should have comment"
    - "comment on exported .* should be of the form"

output:
  format: colored-line-number