// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Suporte API",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/b3/fetch/historical": {
            "post": {
                "description": "Busca e persiste RAW por janelas mensais, evitando duplicidade por hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B3 Data (Persistence)"
                ],
                "summary": "Ingestão histórica de RAW (transactions v2 / positions v3)",
                "parameters": [
                    {
                        "description": "Parâmetros",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/b3.ingestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/b3/fetch/positions/preview": {
            "get": {
                "description": "Busca posições por período e tipo de ativo na B3 e retorna o payload bruto (consolidado), sem persistir.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B3 Data"
                ],
                "summary": "Preview de posições v3 (sem persistência)",
                "parameters": [
                    {
                        "type": "string",
                        "example": "12345678901",
                        "description": "CPF (11 dígitos)",
                        "name": "cpf",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2024-01-01",
                        "description": "Data inicial (YYYY-MM-DD)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2024-01-31",
                        "description": "Data final (YYYY-MM-DD)",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "equity",
                        "description": "Tipo de ativo (equity...) — somente equity implementado agora",
                        "name": "assetType",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "Página inicial (\u003e= 1), padrão 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "example": false,
                        "description": "Se true, pagina até o fim",
                        "name": "fetchAllPages",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exemplo de sucesso",
                        "schema": {
                            "$ref": "#/definitions/dto.PositionsPreviewResponse"
                        }
                    },
                    "400": {
                        "description": "Parâmetros inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Não autorizado / Token inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Acesso negado / Sem permissão",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "Limite de requisições excedido (Retry-After)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/b3/fetch/transactions/preview": {
            "get": {
                "description": "Busca transações por período e tipo de ativo na B3 e retorna o payload bruto (consolidado), sem persistir.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B3 Data"
                ],
                "summary": "Preview de transações v2 (sem persistência)",
                "parameters": [
                    {
                        "type": "string",
                        "example": "12345678901",
                        "description": "CPF (11 dígitos)",
                        "name": "cpf",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2024-01-01",
                        "description": "Data inicial (YYYY-MM-DD)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2024-01-31",
                        "description": "Data final (YYYY-MM-DD)",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "equity",
                        "description": "Tipo de ativo (equity|fii|bdr|...) — somente equity implementado agora",
                        "name": "assetType",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "Página inicial (\u003e= 1), padrão 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "example": false,
                        "description": "Se true, pagina até o fim",
                        "name": "fetchAllPages",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exemplo de sucesso",
                        "schema": {
                            "$ref": "#/definitions/dto.TransactionsPreviewResponse"
                        }
                    },
                    "400": {
                        "description": "Parâmetros inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/b3/health/auth": {
            "get": {
                "description": "Verifica se as variáveis de ambiente de auth estão presentes (não valida contra B3)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "B3"
                ],
                "summary": "B3 auth health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Verifica se a aplicação e seus serviços dependentes estão funcionando",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/controllers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/live": {
            "get": {
                "description": "Verifica se a aplicação está viva (para Kubernetes)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Verifica se a aplicação está pronta para receber requisições",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/wallets": {
            "get": {
                "description": "Lista carteiras com filtros opcionais e paginação",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Listar carteiras",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do inquilino",
                        "name": "X-Tenant-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do proprietário",
                        "name": "owner_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status da carteira",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tipo da carteira",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limite por página",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Busca por nome",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Campo para ordenação",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Ordenação decrescente",
                        "name": "sort_desc",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ListWalletsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma nova carteira digital para um usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Criar carteira",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do inquilino",
                        "name": "X-Tenant-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Dados da carteira",
                        "name": "wallet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.WalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/wallets/owner/{owner_id}": {
            "get": {
                "description": "Busca todas as carteiras de um proprietário específico",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Buscar carteiras por proprietário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do inquilino",
                        "name": "X-Tenant-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do proprietário",
                        "name": "owner_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.WalletResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/wallets/{id}": {
            "get": {
                "description": "Busca uma carteira específica por ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Buscar carteira",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do inquilino",
                        "name": "X-Tenant-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID da carteira",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza uma carteira existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Atualizar carteira",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do inquilino",
                        "name": "X-Tenant-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID da carteira",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualização",
                        "name": "wallet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.WalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove uma carteira (soft delete)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Deletar carteira",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do inquilino",
                        "name": "X-Tenant-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID da carteira",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "b3.ingestRequest": {
            "type": "object",
            "required": [
                "cpf",
                "dataType",
                "end",
                "start"
            ],
            "properties": {
                "assetType": {
                    "description": "default: equity",
                    "type": "string"
                },
                "cpf": {
                    "type": "string"
                },
                "dataType": {
                    "description": "transactions|positions",
                    "type": "string"
                },
                "dryRun": {
                    "type": "boolean"
                },
                "end": {
                    "type": "string"
                },
                "fetchAllPages": {
                    "type": "boolean"
                },
                "force": {
                    "type": "boolean"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "controllers.HealthResponse": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dto.PositionsPreviewResponse": {
            "type": "object",
            "properties": {
                "asset_type": {
                    "type": "string"
                },
                "end": {
                    "type": "string"
                },
                "pages": {
                    "type": "integer"
                },
                "payloads": {
                    "type": "array",
                    "items": {}
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "dto.TransactionsPreviewResponse": {
            "type": "object",
            "properties": {
                "asset_type": {
                    "type": "string"
                },
                "end": {
                    "type": "string"
                },
                "pages": {
                    "type": "integer"
                },
                "payloads": {
                    "type": "array",
                    "items": {}
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateWalletRequest": {
            "type": "object",
            "required": [
                "created_by",
                "currency",
                "name",
                "owner_id",
                "owner_type",
                "tenant_id",
                "type"
            ],
            "properties": {
                "allow_debit": {
                    "type": "boolean"
                },
                "created_by": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "daily_limit": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "is_default": {
                    "type": "boolean"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "monthly_limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "owner_id": {
                    "type": "string"
                },
                "owner_type": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "personal",
                        "business",
                        "corporate"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/entities.WalletType"
                        }
                    ]
                }
            }
        },
        "dtos.ListWalletsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.WalletResponse"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/dtos.PaginationMeta"
                }
            }
        },
        "dtos.PaginationMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "dtos.UpdateWalletRequest": {
            "type": "object",
            "required": [
                "id",
                "tenant_id"
            ],
            "properties": {
                "allow_debit": {
                    "type": "boolean"
                },
                "daily_limit": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_default": {
                    "type": "boolean"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "monthly_limit": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/entities.WalletStatus"
                },
                "tenant_id": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "dtos.WalletResponse": {
            "type": "object",
            "properties": {
                "allow_debit": {
                    "type": "boolean"
                },
                "balance": {
                    "type": "integer"
                },
                "balance_in_reais": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "daily_limit": {
                    "type": "integer"
                },
                "daily_limit_reais": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_default": {
                    "type": "boolean"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "monthly_limit": {
                    "type": "integer"
                },
                "monthly_limit_reais": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "owner_type": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/entities.WalletStatus"
                },
                "tenant_id": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/entities.WalletType"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "entities.WalletStatus": {
            "type": "string",
            "enum": [
                "active",
                "inactive",
                "blocked",
                "suspended"
            ],
            "x-enum-varnames": [
                "WalletStatusActive",
                "WalletStatusInactive",
                "WalletStatusBlocked",
                "WalletStatusSuspended"
            ]
        },
        "entities.WalletType": {
            "type": "string",
            "enum": [
                "personal",
                "business",
                "corporate"
            ],
            "x-enum-varnames": [
                "WalletTypePersonal",
                "WalletTypeBusiness",
                "WalletTypeCorporate"
            ]
        }
    },
    "securityDefinitions": {
        "TenantID": {
            "description": "ID do inquilino para multi-tenancy",
            "type": "apiKey",
            "name": "X-Tenant-ID",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Suno Wallets API",
	Description:      "Sistema de carteiras digitais multi-tenant desenvolvido em Go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
